### ISSUE TITLE
Mongodb version of it?

### ISSUE THREAD

**Issue by coodoo** [cpsubrian/redis-explorer#2]
Thanks for the great app, just wondering is it possible to support mongodb too?

**Comment by cpsubrian** [comment]
I don't think I'd bake multiple-db support into one app, but its possible that I or someone could reuse the basic app code/layout to display mongodb documents. To be totally honest its not something I'm likely to tackle any time soon. There are many many features left to finish in this first :)

For my purposes, I've found [RoboMongo](http://robomongo.org/) to be a pretty functional MongoDB gui, when the command line doesn't suffice.
